
[install]
registry = "https://registry.npmjs.org/"
optional = false
exact = true
cache = false

[install.scopes]
"@electron" = { registry = "https://registry.npmjs.org/" }

[install.git]
enabled = false
