
[install]
# Force registry usage and disable optional deps
registry = "https://registry.npmjs.org/"
optional = false
exact = true
cache = false

[install.scopes]
"@electron" = { registry = "https://registry.npmjs.org/" }

# Disable git protocol entirely to prevent cloning repos like @electron/node-gyp
[install.git]
enabled = false
