
[install]
# Force registry usage and disable git dependencies
registry = "https://registry.npmjs.org/"
optional = false
exact = true
cache = false
git = false

[install.scopes]
"@electron" = { registry = "https://registry.npmjs.org/" }

# Disable git protocol entirely
[install.git]
enabled = false
