
[install]
# Force registry usage and disable git dependencies
optional = false
exact = true
cache = false
git = false

[install.scopes]
"@electron" = { registry = "https://registry.npmjs.org/" }

# Electron specific configuration
electron_rebuild = false

# Force all packages to use registry
[install.registry]
url = "https://registry.npmjs.org/"

# Disable git protocol entirely
[install.git]
enabled = false
